### ISSUE TITLE
add_restraints.r file missing

### ISSUE THREAD

**Issue by jariwalask** [xinqyao/hla#1]
`add_restraints.r` file is missing in dir `complex_prepare`. I found an older version, but that's for gromacs.

**Comment by xinqyao** [comment]
I thought I've already added. Will check shortly.

**Comment by xinqyao** [comment]
Now added

**Comment by jariwalask** [comment]
Fixed by @xinqyao  in 7eaf192fae9030d2484627e725cbcefdea06fa27
